/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t volatile *pClkCtrlReg = (uint32_t*) 0x40023830;
	uint32_t volatile *pPortCModeReg = (uint32_t*) 0x40020800;
	uint32_t volatile *pPortCOutReg = (uint32_t*) 0x40020814;

	uint32_t volatile *pPortAModeReg = (uint32_t *)0x40020000;
	uint32_t volatile *pPortAInReg = (uint32_t *)0x40020000;

	//1) Habilitar el clock para periferico GPIOC en el AHB1ENR
	*pClkCtrlReg |= (1 << 3);
	*pClkCtrlReg |= (1 << 0);

	//Configurando P12 como salida
	*pPortCModeReg &= ~(3 << 24);
	//b. Setear la posicion 24 a 1 (HIGH)
	*pPortCModeReg |= (1 << 24);

	//Configurando PA0 como entrada
	*pPortAModeReg &= ~(3 << 0);

	//Leer el estado de pin PA0
	uint8_t pinStatus = (uint8_t)(*pPortAInReg & 0x1);

	while(1){
		if(pinStatus){
			//Encendemos LED
			*pPortCOutReg |= (1 << 12);
		}else{
			//Apagamos LED
			*pPortCOutReg &= ~(1 << 12);
		}
	}
}
