/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SVC_Handler_c(uint32_t *pBaseStackFrame);

int32_t add_numbers(int32_t x, int32_t y){
	int32_t res;
	__asm volatile ("SVC #36");
	__asm volatile ("MOV %0,R0":"=r"(res)::);
	return res;
}

int32_t sub_numbers(int32_t x, int32_t y){
	int32_t res;
	__asm volatile ("SVC #37");
	__asm volatile ("MOV %0,R0":"=r"(res)::);
	return res;
}

int32_t mul_numbers(int32_t x, int32_t y){
	int32_t res;
	__asm volatile ("SVC #38");
	__asm volatile ("MOV %0,R0":"=r"(res)::);
	return res;
}

int32_t div_numbers(int32_t x, int32_t y){
	int32_t res;
	__asm volatile ("SVC #39");
	__asm volatile ("MOV %0,R0":"=r"(res)::);
	return res;
}

int main(void)
{
	int32_t res;

	res = add_numbers(40,-90);
	printf("Add result = %ld\n",res);

	res = add_numbers(25,150);
	printf("Sub result = %ld\n",res);

	res = add_numbers(374,890);
	printf("Mul result = %ld\n",res);

	res = add_numbers(67,-3);
	printf("Div result = %ld\n",res);
    /* Loop forever */
	for(;;);
}

__attribute((naked)) void SVC_Handler(void){
	//1. Obtener el valor del MSP.
	__asm("MRS R0,MSP");
	__asm("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame){
	printf("in SVC handler\n");

	int32_t arg0,arg1,res;

	uint8_t *pReturn_addr = (uint8_t*)pBaseOfStackFrame[6];

	//2. Decrementar la dirección de retorno por 2 para apuntar
	//al opcode de la instrucción SVC en la memoria de programa.
	pReturn_addr -= 2;

	uint8_t svc_number = *pReturn_addr;

	printf("El número SVC es :%d\n",svc_number);

	arg0 = pBaseOfStackFrame[0];
	arg1 = pBaseOfStackFrame[1];

	switch(svc_number){
		case 36:
			res = arg0 + arg1;
			break;
		case 37:
			res = arg0 - arg1;
			break;
		case 38:
			res = arg0 * arg1;
			break;
		case 39:
			res = arg0/arg1;
			break;
		default:
				printf("Código SVC invalido\n");
	}
	pBaseOfStackFrame[0] = res;
}
