/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#define ALIAS_BASE 0x22000000U
#define BITBAND_BASE 0x20000000U

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint8_t  *ptr = (uint8_t*) 0x20000200;
	*ptr = 0xff;
	//Metodo normal
	//Limpio el 7th posicion de bit
	*ptr &= ~(1 << 7);

	//Reset a 0xff
	*ptr = 0xff;

	//Metodo bit band
	uint8_t* alias_addr = (uint8_t*) (ALIAS_BASE+(32 * (0x20000200 - BITBAND_BASE)) + 7*4);
	//Limpiando 7th bit de direccion 0x20000200
	*alias_addr = 0;

	/* Loop forever */
	for(;;);
}
