/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define IRQNO_TIMER2 	28
#define IRQNO_I2C1 		31

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t *pNVIC_IPRBase 	= (uint8_t*)0xE000E400;
uint8_t *pNVIC_ISERBase = (uint8_t*)0xE000E100;
uint8_t *pNVIC_ISPRBase = (uint8_t*)0XE000E200;


void configure_priority_irqs(uint8_t irq_no,uint8_t priority_value){
	//1. Encontrar iprx
	uint8_t iprx 	= irq_no / 4;
	uint32_t *ipr 	= pNVIC_IPRBase + iprx;

	//2. Posicionarse en iprx
	uint8_t pos 	= (irq_no % 4) * 8;

	//3. Configurar la prioridad
	*ipr &= ~(0xFF << pos); //Clear
	*ipr |= (priority_value << pos);
}

int main(void)
{
	//1. Configurar la prioridad para los periféricos.
	configure_priority_irqs(IRQNO_TIMER2,0x80);
	configure_priority_irqs(IRQNO_I2C1,0x70);

	//2. Establecer el bit de interrupcion pendiente en el NVIC PR
	*pNVIC_ISPRBase |= (1 << IRQNO_TIMER2);

	//3. Habilitar el ISER IRQs en NVIC
	*pNVIC_ISERBase |= (1 << IRQNO_I2C1);
	*pNVIC_ISERBase |= (1 << IRQNO_TIMER2);


    /* Loop forever */
	for(;;);
}

void TIM2_IRQHandler(void){
	printf("[TIM2_IRQHandler]\n");
	*pNVIC_ISPRBase |= (1 << IRQNO_I2C1);
	while(1);
}

void I2C1_EV_IRQHandler(void){
	printf("[I2C1_EV_IRQHandler]\n");
}
