/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	__asm("SVC #8");

	//register uint32_t data __asm("r0");
	uint32_t data;
	__asm volatile("MOV %0,R0": "=r"(data)::);

	printf("data = %ld\n",data);
    /* Loop forever */
	for(;;);
}

__attribute((naked)) void SVC_Handler(void){
	//1. Obtener el valor del MSP.
	__asm("MRS R0,MSP");
	__asm("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame){
	printf("in SVC handler\n");
	uint8_t *pReturn_addr = (uint8_t*)pBaseOfStackFrame[6];

	//2. Decrementar la dirección de retorno por 2 para apuntar
	//al opcode de la instrucción SVC en la memoria de programa.
	pReturn_addr -= 2;

	uint8_t svc_number = *pReturn_addr;

	printf("El número SVC es :%d\n",svc_number);

	svc_number += 4;

	pBaseOfStackFrame[0] = svc_number;
}
